### ISSUE TITLE
xml2array方法有点小问题，建议修改下

### ISSUE THREAD

**Issue by dreamsleet** [lampnick/wxpay-refund-notify-decrypt-helper#3]
@lampnick 首先表示感谢！已拿来使用~ 使用中发现xml2array方法会报个小问题:
Undefined index: value

foreach ($values as $val) {
            $result[strtolower($val['tag'])] = isset($val['value']) ? : '';
        }

**Comment by lampnick** [comment]
@dreamsleet 感谢！
